import { readFileSync } from "node:fs";
import { afterEach, describe, expect, test } from "vitest";
import { getWireIdentity, resetWireIdentityForTests, setWireIdentity } from "../../ai/src/wire-identity.ts";
import { APP_NAME } from "../src/config.ts";
import {
	ACCEPTED_SHIM_BANNER_PREFIXES,
	GENERATED_SHIM_BANNER,
	hasGeneratedShimBanner,
} from "../src/core/generated-shim-banner.ts";
import { getPiUserAgent } from "../src/utils/pi-user-agent.ts";

describe("wire identity", () => {
	afterEach(() => {
		resetWireIdentityForTests();
	});

	test("defaults to the engine identity", () => {
		expect(getWireIdentity()).toBe("senpi");
	});

	test("takes the product token a distribution sets at startup", () => {
		setWireIdentity("omo");

		expect(getWireIdentity()).toBe("omo");
	});

	test("ignores an empty token instead of blanking the wire identity", () => {
		setWireIdentity("   ");

		expect(getWireIdentity()).toBe("senpi");
	});

	test("user agent names the running product", () => {
		expect(getPiUserAgent("1.2.3")).toContain(`${APP_NAME}/1.2.3`);
	});
});

describe("generated shim banner", () => {
	test("writes the running product name", () => {
		expect(GENERATED_SHIM_BANNER).toContain(`Generated by ${APP_NAME}.`);
	});

	test("still recognises shims written by earlier brands", () => {
		expect(
			hasGeneratedShimBanner(
				"// Generated by senpi. Delete this file to stop loading the default global extension.\n",
			),
		).toBe(true);
		expect(
			hasGeneratedShimBanner(
				"// Generated by pi-coding-agent. Delete this file to stop loading the default global extension.\n",
			),
		).toBe(true);
		expect(hasGeneratedShimBanner(GENERATED_SHIM_BANNER)).toBe(true);
	});

	test("leaves user-authored extensions alone", () => {
		expect(hasGeneratedShimBanner("export default function () {}\n")).toBe(false);
		expect(ACCEPTED_SHIM_BANNER_PREFIXES.length).toBeGreaterThan(0);
	});

	test("the reload filter and the writer share one banner source", () => {
		const filter = readFileSync(
			new URL("../src/core/extensions/builtin/config-reload/generated-shim-filter.ts", import.meta.url),
			"utf-8",
		);

		expect(filter).toContain("generated-shim-banner.ts");
		expect(filter).not.toContain('"// Generated by senpi."');
	});
});
