/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class PtySession {
  constructor()
}
export type NativePtySession = PtySession

export declare function __senpiPtyV2026_7_5(): string

export declare function version(): string
