// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/chatgpt-subscription.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const CHATGPT_SUBSCRIPTION_MODELS: ModelCatalog<typeof values, "chatgpt-subscription"> =
	flattenModelCatalog("chatgpt-subscription", values);
