// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/commandcode.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const COMMANDCODE_MODELS: ModelCatalog<typeof values, "commandcode"> =
	flattenModelCatalog("commandcode", values);
