// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const FUGU_MODELS = {
	"fugu": {
		id: "fugu",
		name: "Sakana Fugu",
		api: "openai-completions",
		provider: "fugu",
		baseUrl: "https://api.sakana.ai/v1",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":false,"maxTokensField":"max_tokens"},
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 200000,
		maxTokens: 65536,
	} satisfies Model<"openai-completions">,
} as const;
