// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const GLM_ZCODE_MODELS = {
	"glm-5.2": {
		id: "glm-5.2",
		name: "GLM-5.2 (ZCode)",
		api: "anthropic-messages",
		provider: "glm-zcode",
		baseUrl: "https://api.z.ai/api/anthropic",
		headers: {
			"User-Agent": "ZCode/3.1.2",
			"X-Title": "Z Code@electron",
			"HTTP-Referer": "https://zcode.z.ai",
			"X-ZCode-Agent": "glm",
			"X-ZCode-App-Version": "3.1.2",
			"X-Release-Channel": "production",
		},
		reasoning: true,
		thinkingLevelMap: { minimal: null, low: "high", medium: "high", high: "high", max: "max" },
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1000000,
		maxTokens: 131072,
	} satisfies Model<"anthropic-messages">,
} as const;
