// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const KAGI_MODELS = {
	"search": {
		id: "search",
		name: "Kagi Search (credential placeholder)",
		api: "openai-completions",
		provider: "kagi",
		baseUrl: "https://kagi.com/api/v0",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":false,"supportsUsageInStreaming":false,"maxTokensField":"max_tokens","supportsStrictMode":false,"supportsLongCacheRetention":false},
		reasoning: false,
		input: ["text"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 8192,
		maxTokens: 1024,
	} satisfies Model<"openai-completions">,
} as const;
