// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const NANOGPT_MODELS = {
	"openai/gpt-5.4": {
		id: "openai/gpt-5.4",
		name: "GPT-5.4",
		api: "openai-completions",
		provider: "nanogpt",
		baseUrl: "https://nano-gpt.com/api/v1",
		reasoning: true,
		thinkingLevelMap: {"xhigh":"xhigh"},
		input: ["text", "image"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 1050000,
		maxTokens: 128000,
	} satisfies Model<"openai-completions">,
} as const;
