// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/neuralwatt.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const NEURALWATT_MODELS: ModelCatalog<typeof values, "neuralwatt"> =
	flattenModelCatalog("neuralwatt", values);
