// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const QIANFAN_MODELS = {
	"deepseek-v3.2": {
		id: "deepseek-v3.2",
		name: "DeepSeek V3.2",
		api: "openai-completions",
		provider: "qianfan",
		baseUrl: "https://qianfan.baidubce.com/v2",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"maxTokensField":"max_tokens","supportsStrictMode":false},
		reasoning: false,
		input: ["text"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 98304,
		maxTokens: 32768,
	} satisfies Model<"openai-completions">,
} as const;
