// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const QWEN_PORTAL_MODELS = {
	"coder-model": {
		id: "coder-model",
		name: "Qwen Coder",
		api: "openai-completions",
		provider: "qwen-portal",
		baseUrl: "https://portal.qwen.ai/v1",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"maxTokensField":"max_tokens"},
		reasoning: false,
		input: ["text"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 128000,
		maxTokens: 8192,
	} satisfies Model<"openai-completions">,
} as const;
