// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const SYNTHETIC_MODELS = {
	"hf:moonshotai/Kimi-K2.5": {
		id: "hf:moonshotai/Kimi-K2.5",
		name: "moonshotai/Kimi-K2.5",
		api: "openai-completions",
		provider: "synthetic",
		baseUrl: "https://api.synthetic.new/openai/v1",
		compat: {"supportsStore":false,"supportsDeveloperRole":false},
		reasoning: false,
		input: ["text"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 8192,
	} satisfies Model<"openai-completions">,
} as const;
