// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const VENICE_MODELS = {
	"llama-3.3-70b": {
		id: "llama-3.3-70b",
		name: "Llama 3.3 70B",
		api: "openai-completions",
		provider: "venice",
		baseUrl: "https://api.venice.ai/api/v1",
		compat: {"supportsUsageInStreaming":false},
		reasoning: false,
		input: ["text"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 128000,
		maxTokens: 8192,
	} satisfies Model<"openai-completions">,
} as const;
