// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const ZENMUX_MODELS = {
	"anthropic/claude-opus-4.6": {
		id: "anthropic/claude-opus-4.6",
		name: "Anthropic Opus 4.6",
		api: "anthropic-messages",
		provider: "zenmux",
		baseUrl: "https://zenmux.ai/api/anthropic",
		compat: {"forceAdaptiveThinking":true},
		reasoning: true,
		thinkingLevelMap: {"max":"max"},
		input: ["text", "image"],
		cost: {
			input: 5,
			output: 25,
			cacheRead: 0.5,
			cacheWrite: 6.25,
		},
		contextWindow: 1000000,
		maxTokens: 128000,
	} satisfies Model<"anthropic-messages">,
} as const;
